services:
  - type: web
    name: esctrix
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT --workers 1 --ws websockets
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DB_PATH
        value: "users.db"
      - key: RENDER
        value: "true"
